### ISSUE TITLE
Angular 15 support

### ISSUE THREAD

**Issue by seawave23** [arnaudleclerc/ng-azure-maps#81]
Hello, we just updated our project to Angular 15, and realized that this one package is not working with it: 
![image](https://user-images.githubusercontent.com/25248695/233941532-ae6de866-158e-42ad-afb7-ecf6c4444ae0.png)

Is there a chance that this project will be updated or is there any suggestion for a replacement?

**Comment by arnaudleclerc** [comment]
I just published a version 7.0.0-beta.1 built on angular 15. Do you mind giving it a try and giving me feedback ? If this version works for you, I will publish a stable version.

**Comment by seawave23** [comment]
Wow, that was fast! 
I investigated our issue in the meantime and found out that it throws when setting the bounds input variable in the azure map, as well as when I'm resizing the page with the map.
I will give it a try in the next minutes and will report if the socket-io version update helped. Thanks a lot for keeping the package alive!

**Comment by seawave23** [comment]
@arnaudleclerc: 
Unfortunately, our problem is still there, and reproducible. We have a toggle that toggles the type of address from coordinates to address. When the user switches the address type, for the coordinates, a matching address is retrieved with the first result of SearchService's searchAddressReverse which contains a viewport. The viewport is passed to the bounds input of the map, transformed like this:

 this.bounds = [
        viewport.topLeft.longitude, 
        viewport.topLeft.latitude,
        viewport.bottomRight.longitude,
        viewport.bottomRight.latitude,
      ];

Then, the setCamera in the map gets called and throws.
Is there probably an error in our mapping which now throws, but before didn't?

**Comment by Pandolfou** [comment]
> I just published a version 7.0.0-beta.1 built on angular 15. Do you mind giving it a try and giving me feedback ? If this version works for you, I will publish a stable version.

Hi, I am upgrading my application to angular 15 and try the beta release of ng-azure-maps. All works fine on my side. We have a simple implementation that display locations by coordinates with bubble layers.
